const PAYMENT_STATUS = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED'
};

const PAYMENT_FAILURE_REASONS = {
  CART_EMPTY: 'CART_EMPTY',
  STOCK_ISSUE: 'STOCK_ISSUE',
  INSUFFICIENT_WALLET_BALANCE: 'INSUFFICIENT_WALLET_BALANCE',
  PAYMENT_CANCELLED: 'PAYMENT_CANCELLED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  GATEWAY_ERROR: 'GATEWAY_ERROR'
};

module.exports = {
  PAYMENT_STATUS,
  PAYMENT_FAILURE_REASONS
};
